export const types = {
  CHANGE_NAME: 'CHANGE_NAME',
  SUCCESSFUL_LOAD_DATA: 'SUCCESSFUL_LOAD_DATA',
  ERROR_LOAD_DATA: 'ERROR_LOAD_DATA',
  LOADING_DATA: 'LOADING_DATA',

  SEARCH_BY_BREED: 'SEARCH_BY_BREED',
};
